apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: server-web
        image: gcr.io/finaldesopes1/appdeweb:1.0
        ports:
        - containerPort: 4200
